import json
from pathlib import Path

# Paths to our files
INPUT_LOG_FILE = Path("data/raw_logs/collected_logs.json")
OUTPUT_PARSED_FILE = Path("data/raw_logs/parsed_logs.json")

def read_collected_logs():
    """Reads the JSON file generated by log_collector.py."""
    if not INPUT_LOG_FILE.exists():
        print(f"[!] Error: Cannot find {INPUT_LOG_FILE}.")
        print("    Did you run 'python src/log_collector.py' first?")
        return []

    try:
        with open(INPUT_LOG_FILE, "r") as f:
            data = json.load(f)
            return data.get("Records", [])
    except Exception as e:
        print(f"[!] Failed to read logs: {e}")
        return []

def parse_event(event):
    """
    Takes a massive AWS CloudTrail JSON event and simplifies it.
    We 'flatten' some of the nested dictionaries so it's easier to read later.
    """
    # Create an empty dictionary to hold our simplified data
    parsed_record = {}

    # Extract standard fields (if they don't exist, we default to 'Unknown')
    parsed_record["event_time"] = event.get("eventTime", "Unknown")
    parsed_record["event_name"] = event.get("eventName", "Unknown")
    parsed_record["aws_region"] = event.get("awsRegion", "Unknown")
    parsed_record["source_ip"] = event.get("sourceIPAddress", "Unknown")
    
    # User Identity is sometimes nested (e.g., event["userIdentity"]["userName"])
    # We must be careful because some bot events don't have a 'userName'
    user_identity = event.get("userIdentity", {})
    
    # Try different fields AWS uses for usernames (userName, principalId, etc.)
    user_name = user_identity.get("userName", "Unknown")
    if user_name == "Unknown":
        user_name = user_identity.get("principalId", "Unknown")
        
    parsed_record["user_name"] = user_name
    parsed_record["user_type"] = user_identity.get("type", "Unknown")

    # If the action failed (e.g., AccessDenied), CloudTrail logs an errorCode
    parsed_record["error_code"] = event.get("errorCode", "None")

    return parsed_record

def parse_all_logs():
    """Reads all logs, parses them one by one, and saves the cleaned log list."""
    print("--- Starting Log Parser ---")
    
    raw_records = read_collected_logs()
    if not raw_records:
        return []
        
    print(f"[i] Found {len(raw_records)} events to parse.")

    parsed_records = []
    # Loop through every massive JSON log and simplify it
    for record in raw_records:
        clean_record = parse_event(record)
        parsed_records.append(clean_record)

    # Save the huge list of cleaned records to a new JSON file
    with open(OUTPUT_PARSED_FILE, "w") as f:
        json.dump(parsed_records, f, indent=2)

    print(f"[+] Success! Cleaned and flattened {len(parsed_records)} events.")
    print(f"[+] Saved parsed data to {OUTPUT_PARSED_FILE}")
    
    return parsed_records

# This block runs only if you run this file directly in the terminal
if __name__ == "__main__":
    parse_all_logs()
